<?php

use App\Entities\Client;
use App\Repositories\ClientRepository;
use PHPUnit\Framework\TestCase;

class ClientRepositoryTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = new Client();
        $this->clientRepository = new ClientRepository($this->client);
    }

    public function testSave()
    {
        $response = $this->clientRepository->save(1, 'Fernando');

        $this->assertEquals('Fernando', $response['name']);
    }

    public function testGet()
    {
        $response = $this->clientRepository->get();

        $this->assertIsArray($response);
    }

    public function testGetByName()
    {
        $response = $this->clientRepository->getByName('Fernando');

        $this->assertIsArray($response);
        $this->assertEquals('Fernando', $response[0]['name']);
    }
}